import { describe, expect, it } from 'vitest';
import { preparePointsSnapshot } from '../pointsSnapshots';

const pointsInput = {
  ageBracket: '25-32', englishLevel: 'Proficient', overseasSkilledEmploymentYears: '3-4', australianSkilledEmploymentYears: '1-2',
  highestQualificationLevel: 'Bachelor/Masters', australianStudyRequirementCompleted: 'Yes', regionalStudyCompleted: 'No',
  specialistEducationalQualification: 'No', professionalYearCompleted: 'No', naatiCredential: 'No',
  partnerPointsCategory: 'Single or partner is AU citizen/PR', nominationType: 'None', englishTestCompleted: 'Yes',
  migrationOccupation: 'Developer', workExperienceYears: '4', completionYear: '2018',
} as const;

describe('preparePointsSnapshot', () => {
  it('prepares snapshot with calculator version', () => {
    const snapshot = preparePointsSnapshot({ pointsInput, calculatorVersion: 'v-test', generatedBy: 'reviewer-1' });
    expect(snapshot.calculatorVersion).toBe('v-test');
  });
  it('includes input payload', () => {
    const snapshot = preparePointsSnapshot({ pointsInput, generatedBy: 'reviewer-1' });
    expect(snapshot.inputPayload).toEqual(pointsInput);
  });
  it('includes estimated total points', () => {
    const snapshot = preparePointsSnapshot({ pointsInput, generatedBy: 'reviewer-1' });
    expect(typeof snapshot.estimatedTotal).toBe('number');
  });
  it('includes breakdown', () => {
    const snapshot = preparePointsSnapshot({ pointsInput, generatedBy: 'reviewer-1' });
    expect(snapshot.pointsBreakdown).toHaveProperty('age');
  });
  it('includes generated timestamp and generated by', () => {
    const now = new Date('2026-01-01T00:00:00.000Z');
    const snapshot = preparePointsSnapshot({ pointsInput, generatedBy: 'reviewer-2', generatedAt: now });
    expect(snapshot.generatedBy).toBe('reviewer-2');
    expect(snapshot.generatedAt).toBe(now.toISOString());
  });
});
